name:                remote-calculator
version:             0.1.0.0
github:              "arkon92/remote-calculator"
author:              "arkon92"

extra-source-files:
- README.md


description:         Simple calculator available via TCP.

dependencies:
- base >= 4.7 && < 5
- network

library:
  source-dirs: src

executables:
  remote-calculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - remote-calculator